name: Build Client Photo Controls

on:
  workflow_dispatch:
  push:
    branches: [client-photo-controls-26.2]

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Project files are being staged."
